<h2>Agregar Cuenta</h2>
<div class="container">
	<div class="col-md-12">
		<form action="<?php 
		/**
		 * add.phtml
		 */
		echo APP_URL.'accounts/add'; ?>" method="POST">
			<label for="nombre">Nombre</label>
			<div class="input-group">			
				<input type="text" name="name" class="form-control">
				<div class="input-group-append">
					<button class="btn btn-sm btn-success" action="submit">Agregar</button>
				</div>
			</div>
		</form>
	</div>
</div>